---

- name: Make sure swap is off
  ansible.builtin.raw: swapoff -a

- name: Make sure swap stays off after reboot
  ansible.builtin.raw: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Add kernel module overlay to /etc/modules-load.d/containerd.conf and create the file if nonexistant
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: overlay
    create: yes
  notify:
    - Make sure module overlay is loaded

- name: Add kernel module br_netfilter to /etc/modules-load.d/containerd.conf and create the file if nonexistant
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: br_netfilter
    create: yes
  notify:
    - Make sure module br_netfilter is loaded

- name: Copy configuration file for the critical kernel parameters for Kubernetes
  ansible.builtin.copy:
    src: files/etc/sysctl.d/60-kubernetes.conf
    dest: /etc/sysctl.d/60-kubernetes.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload sysctl changes

- name: Make sure all nesessary software requisites are available
  ansible.builtin.apt:
    pkg:
    - curl
    - gnupg2
    - software-properties-common
    - apt-transport-https
    - ca-certificates

- name: Make sure the Docker gpg key is installed
  ansible.builtin.raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

- name: Copy the Docker repository file with correct permissions
  ansible.builtin.copy:
    src: files/etc/apt/sources.list.d/docker_com_linux_ubuntu-noble.list
    dest: /etc/apt/sources.list.d/docker_com_linux_ubuntu-noble.list
    owner: root
    group: root
    mode: '0644'

- name: Update the repository cache and update package "containerd.io" to latest version
  ansible.builtin.apt:
    name: containerd.io
    state: latest
    update_cache: yes

- name: Configure containerd to start using systemd as cgroup
  ansible.builtin.raw: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1

- name: Configure containerd to start using systemd as cgroup 2
  ansible.builtin.raw: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: Enable a timer unit for dnf-automatic
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true

...
